Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2023-11, with the labels that each got.

#151 fix(event-reduce): add reduce logic to recover expired transaction
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionExpired.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java
Labels: size/small, patch

#152 [CHK-2095] feat: added new method saveIfAbsent into RedisTemplateWrapper
  src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java
  src/test/java/it/pagopa/ecommerce/commons/redis/v1/templatewrappers/PaymentRequestInfoRedisTemplateWrapperTest.java
  src/test/java/it/pagopa/ecommerce/commons/redis/v2/templatewrappers/PaymentRequestInfoRedisTemplateWrapperTest.java
Labels: size/small, minor

#153 [CHK-1765] fix(tracing): set parent correctly when injecting remote span
  src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
Labels: size/small, patch

#154 feat(npg): [CHK-2113] - PSP api key configuration read porting
  src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgApiKeyConfigurationException.java
  src/main/java/it/pagopa/ecommerce/commons/utils/NpgPspApiKeysConfig.java
  src/test/java/it/pagopa/ecommerce/commons/utils/NpgPspApiKeysConfigTest.java
Labels: minor

#157 refactor(npg): misc NPG refactorings
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgApiKeyMissingPspRequestedException.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgResponseException.java
  src/main/java/it/pagopa/ecommerce/commons/utils/NpgPspApiKeysConfig.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
  src/test/java/it/pagopa/ecommerce/commons/utils/NpgPspApiKeysConfigTest.java
Labels: size/small, patch

#158 fix(release): fix committer in automatic PRs when releasing new version
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, patch

#155 [CHK-2123] feat(npg): update NPG spec to v0.7
  clients/api-specs/npg.yaml
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/large, patch
