Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2023-09, with the labels that each got.

#126 feat(transaction-id): add conversion methods to and from base64 to `TransactionId`
  pom.xml
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionId.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionIdTests.java
Labels: size/small, minor

#125 [CHK-1862] feat(refund): add refund payment method for npg client
  clients/api-specs/npg.yaml
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, patch

#127 fix(NPG openapi): added new element for State enum
  clients/api-specs/npg.yaml
Labels: size/small, patch

#128 fix(PaymentGateway): added new paymentGateway
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
Labels: size/small, minor

#130 Chk 1904 customize v2 events
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionActivatedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationCompletedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/activation/EmptyTransactionGatewayActivationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/activation/NpgTransactionGatewayActivationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/activation/TransactionGatewayActivationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/PgsTransactionGatewayAuthorizationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/TransactionGatewayAuthorizationData.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/EmptyTransaction.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionActivated.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithCompletedAuthorization.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/TransactionDocumentTest.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/large, minor

#131 fix(view): CHK-1904 add version agnostic base class
  src/main/java/it/pagopa/ecommerce/commons/documents/BaseTransactionView.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/Transaction.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/Transaction.java
  src/main/java/it/pagopa/ecommerce/commons/utils/v1/TransactionUtils.java
  src/main/java/it/pagopa/ecommerce/commons/utils/v2/TransactionUtils.java
Labels: size/small, patch

#56 [CHK-1249] feat(release): trigger automatic PR on eCommerce projects on commons release
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, patch

#132 fix(auto-pr): Misc fixes related to Action authorization
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, patch

#133 refactor(auto-pr): use action to create commit
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, skip-release

#134 fix(versioning): un-version RedisTemplateWrapper class
  src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java
  src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/v1/PaymentRequestInfoRedisTemplateWrapper.java
  src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/v2/PaymentRequestInfoRedisTemplateWrapper.java
  src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/v2/RedisTemplateWrapper.java
Labels: size/small, patch

#136 refactor(auto-pr): trigger action on tag push rather than on release publishing
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, skip-release

#137 fix(auto-pr): fix fetch depth when checking out repo
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, skip-release

#138 fix(auto-pr): Refactor action to trigger on GitHub release rather than on tag push
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, skip-release

#139 fix(auto-pr): remove env for action
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, skip-release

#140 feat: add all eCommerce repos to action
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, skip-release

#142 refactor: remove workflow_dispatch on PR action
  .github/workflows/create_pr_with_version_update.yaml
Labels: size/small, skip-release

#144 fix(serialization): add mixin classes for properly serialize/deserialize queue events v2
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/serialization/TransactionEventTypeResolver.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionActivatedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationCompletedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolver.java
  src/main/java/it/pagopa/ecommerce/commons/queues/StrictJsonSerializerProvider.java
  src/main/java/it/pagopa/ecommerce/commons/queues/mixin/deserialization/v1/TransactionEventMixInEventCodeFieldDiscriminator.java
  src/main/java/it/pagopa/ecommerce/commons/queues/mixin/deserialization/v2/TransactionEventMixInClassFieldDiscriminator.java
  src/main/java/it/pagopa/ecommerce/commons/queues/mixin/serialization/v1/QueueEventMixInEventCodeFieldDiscriminator.java
  src/main/java/it/pagopa/ecommerce/commons/queues/mixin/serialization/v2/QueueEventMixInClassFieldDiscriminator.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/queues/StrictJsonSerializerProviderTest.java
Labels: patch

#145 fix: make npg constants public
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, patch
