Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2023-07, with the labels that each got.

#95 [CHK-1680] add pspOnUs flag
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
  src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Labels: size/small

#96 refactor(events): add `BaseTransactionEvent` as perennial base structure for eCommerce events
  src/main/java/it/pagopa/ecommerce/commons/documents/BaseTransactionEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionEvent.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v1/TransactionDocumentTest.java
Labels: size/small

#97 feat(CD): deploy on PR merge
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/deploy.yml
  README.md
Labels: size/small, skip-release

#98 fix: pr extraction number from commit message
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, skip-release

#101 fix(events): fix Spring annotation in inherited `BaseTransaction`'s fields
  src/main/java/it/pagopa/ecommerce/commons/documents/BaseTransactionEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionEvent.java
Labels: size/small, skip-release

#102 feat(paymentMethodDescription) added payment method description into AuhorizationRequestEvent
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
  src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
Labels: size/small, minor

#104 Fix deploy pipeline trigger
  .github/workflows/deploy.yml
Labels: size/small, minor

#105 fix(deploy-action): fix pipeline trigger
  .github/workflows/deploy.yml
Labels: size/small, minor

#106 chore(deploy-action): test skip release
  foo.txt
Labels: size/small, skip-release

#107 Delete foo.txt
  foo.txt
Labels: size/small, skip-release

#108 fix(mail-validation): make validation case insensitive
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/Email.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v1/EmailTest.java
Labels: size/small, patch

#109 Chk 1712 mail case insensitive
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/Email.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v1/EmailTest.java
Labels: size/small, patch

#94 [CHK-1565] feat(tracing): add class for serialized queue events with embedded tracing info
  pom.xml
  src/main/java/it/pagopa/ecommerce/commons/client/QueueAsyncClient.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/BaseTransactionClosureEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationCompletedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionClosureData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/serialization/TransactionEventTypeResolver.java
  src/main/java/it/pagopa/ecommerce/commons/queues/QueueEvent.java
  src/main/java/it/pagopa/ecommerce/commons/queues/StrictJsonSerializerProvider.java
  src/main/java/it/pagopa/ecommerce/commons/queues/TracingInfo.java
  src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
  src/test/java/it/pagopa/ecommerce/commons/client/QueueAsyncClientTest.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v1/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/queues/StrictJsonSerializerProviderTest.java
  src/test/java/it/pagopa/ecommerce/commons/queues/TracingInfoTest.java
  src/test/java/it/pagopa/ecommerce/commons/queues/TracingUtilsTests.java
Labels: size/large, patch

#110 fix(events): mark `eventCode` field as `visible` for type identification
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionEvent.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v1/serialization/TransactionEventTypeResolverTest.java
Labels: size/small, patch

#111 fix(tracing): don't create a `Scope` when tracing `Mono`s
  src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
Labels: size/small, patch
