Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2023-08, with the labels that each got.

#112 fix(rptId): fix rptid regex
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/RptId.java
Labels: bug, size/small, patch

#114 feat: add base transaction at previous step for transaction with refund requested
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/pojos/BaseTransactionWithRefundRequested.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v1/TransactionTest.java
Labels: size/small, minor

#116 refactor(redis): unseal `RedisTemplateWrapper`
  src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java
Labels: size/small, patch

#117 refactor(redis): make `RedisTemplateWrapper` public
  src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java
Labels: size/small, patch

#115 [CHK-1782] refactor(npg-client): add payment method enumeration to NPG client
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, patch

#119 feat: CHK-1824 client for retrieve card data from NPG
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, minor

#120 [CHK-1787] refactor(npg-client): refactor NPG error logging
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgResponseException.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: patch

#123 fix(openapi): fixed npg api path into openapi
  clients/api-specs/npg.yaml
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, patch

#122 feat(npg): CHK-1833 add confirm payment for npg client
  clients/api-specs/npg.yaml
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, minor
