Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2023-10, with the labels that each got.

#146 feat(logo and circuit): [CHK-1971] handle paymentCircuit for NPG
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationRequestData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/EmptyTransactionGatewayAuthorizationRequestedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/PgsTransactionGatewayAuthorizationRequestedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/TransactionGatewayAuthorizationRequestedData.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: minor

#148 feat(NPG): move logo and brand to authorization requested event
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationRequestedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/TransactionGatewayAuthorizationRequestedData.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, patch

#149 feat: add NPG authorization session id
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/activation/NpgTransactionGatewayActivationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationRequestedData.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, minor

#150 [CHK-1968] feat(npg): improve refund request parameters type
  clients/api-specs/npg.yaml
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientPaymentMethodTests.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, patch
