Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2024-05, with the labels that each got.

#191 feat: add optional details for wallet into NPG auth requested data
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationRequestedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/WalletInfo.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: minor

#192 feat: add `BIN` and `CardLastFourDigits` domain classes
  src/main/java/it/pagopa/ecommerce/commons/domain/BIN.java
  src/main/java/it/pagopa/ecommerce/commons/domain/CardLastFourDigits.java
  src/test/java/it/pagopa/ecommerce/commons/domain/BINTest.java
  src/test/java/it/pagopa/ecommerce/commons/domain/CardLastFourDigitsTest.java
Labels: size/small, patch

#194 feat: add companyName into transaction activated data + removed data from add user receipt
  src/main/java/it/pagopa/ecommerce/commons/documents/PaymentNotice.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionUserReceiptData.java
  src/main/java/it/pagopa/ecommerce/commons/domain/CompanyName.java
  src/main/java/it/pagopa/ecommerce/commons/domain/PaymentNotice.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/EmptyTransaction.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/TransactionActivated.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v1/pojos/BaseTransactionWithPaymentToken.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/EmptyTransaction.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionActivated.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithPaymentToken.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v1/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/queues/StrictJsonSerializerProviderTest.java
  src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, minor

#196 feat(npg): [CHK-2833] Add GET order npg
  clients/api-specs/npg.yaml
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, minor

#197 [CHK-2262] update api npg client
  clients/api-specs/npg.yaml
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: patch

#198 feat: add gateway data for refund requested and refunded transactions
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/BaseTransactionRefundedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/BaseTransactionRetriedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundErrorData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundErrorEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundRequestedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundRequestedEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundRetriedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundRetriedEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRetriedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/refund/EmptyGatewayRefundData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/refund/GatewayRefundData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/refund/NpgGatewayRefundData.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithRefundError.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithRefundRequested.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionRefunded.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithRefundRequested.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/large, minor

#200 fix: add explicit constructor with args
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionRefundErrorData.java
Labels: size/small, patch

#201 fix: [CHK-2879] Remove set parent on tracing remote span for mono
  src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
Labels: size/small, patch

#202 Revert "fix: [CHK-2879] Remove set parent on tracing remote span for mono"
  src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
Labels: size/small, patch

#204 [CHK-2850] fix(tracing): use `ContextPropagationOperator` to propagate otel context
  pom.xml
  src/main/java/it/pagopa/ecommerce/commons/queues/TracingUtils.java
Labels: size/small, patch
