Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2024-03, with the labels that each got.

#182 feat: handle send payment result after expiration for v2 events
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionExpired.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
Labels: size/small, minor

#183 chore(refactoring): refactoring from checkout redirect to redirect + remove unused logic
  src/main/java/it/pagopa/ecommerce/commons/exceptions/CheckoutRedirectConfigurationType.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/RedirectConfigurationException.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/RedirectConfigurationType.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/RedirectMissingPspRequestedException.java
  src/main/java/it/pagopa/ecommerce/commons/utils/CheckoutRedirectPspApiKeysConfig.java
  src/test/java/it/pagopa/ecommerce/commons/utils/CheckoutRedirectPspApiKeysConfigTest.java
Labels: patch

#186 [CHK-2627] fix position of the api key
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, patch
