Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2024-04, with the labels that each got.

#187 fix(tests): use actual valid payment type code in test utils
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/v1/TransactionTestUtils.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, patch

#188 feat: add Npg psp api keys handler
  src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgApiKeyConfigurationException.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgApiKeyMissingPspRequestedException.java
  src/main/java/it/pagopa/ecommerce/commons/utils/NpgApiKeyConfiguration.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/utils/NpgApiKeyConfigurationTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/large, minor

#189 feat: add user id into transaction activated event and view
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/Transaction.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionActivatedData.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/EmptyTransaction.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionActivated.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/queues/StrictJsonSerializerProviderTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, minor

#190 feat: add validationServiceId NPG auth completed field
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationData.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, minor

#193 feat(monitoring): trace NPG http error codes into error span
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, minor
