Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2024-02, with the labels that each got.

#177 fix: remove postepay logic
  src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationRequestData.java
Labels: size/small, patch

#178 fix: make NPG error code decoding lenient
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/NpgResponseException.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: patch

#179 Log node forwarder error response
  src/main/java/it/pagopa/ecommerce/commons/client/NodeForwarderClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NodeForwarderClientTest.java
Labels: size/small, patch

#181 fix: set api key into Node Forwarder api call
  src/main/java/it/pagopa/ecommerce/commons/client/NodeForwarderClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NodeForwarderClientTest.java
Labels: size/small, patch

#180 [CHK-2508] add auth requested retry
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationOutcomeWaitingEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionEvent.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionEventCode.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, minor
