Repository pagopa/pagopa-ecommerce-commons, pull requests merged in 2024-01, with the labels that each got.

#164 feat: add transaction amount for order build call
  src/main/java/it/pagopa/ecommerce/commons/client/NpgClient.java
  src/test/java/it/pagopa/ecommerce/commons/client/NpgClientTests.java
Labels: size/small, minor

#165 feat(redirect): add events data details for redirect transactions
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionAuthorizationRequestData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/RedirectTransactionGatewayAuthorizationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/RedirectTransactionGatewayAuthorizationRequestedData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/TransactionGatewayAuthorizationData.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/TransactionGatewayAuthorizationRequestedData.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithCompletedAuthorization.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/large, minor

#166 [CHK-2321] feat(checkout-redirect): add `CheckoutRedirectPspApiKeysConfig` bean to hold Checkout Redirect PSP API keys
  src/main/java/it/pagopa/ecommerce/commons/exceptions/CheckoutRedirectConfigurationException.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/CheckoutRedirectConfigurationType.java
  src/main/java/it/pagopa/ecommerce/commons/exceptions/CheckoutRedirectMissingPspRequestedException.java
  src/main/java/it/pagopa/ecommerce/commons/utils/CheckoutRedirectPspApiKeysConfig.java
  src/test/java/it/pagopa/ecommerce/commons/utils/CheckoutRedirectPspApiKeysConfigTest.java
Labels: size/small, patch

#170 feat(redis template): [CHK-2388] add ops for stream and for get all entries
  src/main/java/it/pagopa/ecommerce/commons/redis/templatewrappers/RedisTemplateWrapper.java
  src/main/java/it/pagopa/ecommerce/commons/utils/UniqueIdUtils.java
  src/test/java/it/pagopa/ecommerce/commons/redis/v1/templatewrappers/PaymentRequestInfoRedisTemplateWrapperTest.java
Labels: size/small, minor

#169 [CHK 2369] add new closure requested event
  specs/transactions-dtos.yaml
  specs/v1/state_machine.js
  specs/v2/state_machine.js
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionClosureRequestedEvent.java
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/TransactionEvent.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/Transaction.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionAuthorizationCompleted.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionClosed.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionEventCode.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithClosureError.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/TransactionWithClosureRequested.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionClosed.java
  src/main/java/it/pagopa/ecommerce/commons/domain/v2/pojos/BaseTransactionWithClosureRequested.java
  src/test/java/it/pagopa/ecommerce/commons/domain/v2/TransactionTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/large, minor

#173 feat: add gateway authorization status into transactions view
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/Transaction.java
Labels: size/small, minor

#174 feat: add NPG error code into authorization completed data
  src/main/java/it/pagopa/ecommerce/commons/documents/v2/authorization/NpgTransactionGatewayAuthorizationData.java
  src/test/java/it/pagopa/ecommerce/commons/documents/v2/serialization/TransactionEventTypeResolverTest.java
  src/test/java/it/pagopa/ecommerce/commons/v2/TransactionTestUtils.java
Labels: size/small, minor
